language: python

python:
  - 3.7

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - git checkout master
  - python igem-wikisync.py

after_script:
  - git config --global user.email "travis@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git status
  - git add .
  - 'git commit -m "Travis build: $TRAVIS_BUILD_NUMBER" -m "[skip ci]"'
  # Remove existing "origin"
  - git remote rm origin
  # Add new "origin" with access token in the git URL for authentication
  - git remote add origin https://ballaneypranav:${GH_TOKEN}@github.com/igembitsgoa/igem-wikisync-test.git > /dev/null 2>&1
  - git status
  - git push origin master 


# from https://www.vinaygopinath.me/blog/tech/commit-to-master-branch-on-github-using-travis-ci/