language: python

python:
  - 3.7

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - python igem-wikisync.py

after_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout -b master
  - git add .
  - 'git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git push