language: python

python:
  - 3.7

git:
  depth: false

# install:
  # - pip install -r requirements.txt

script:
  - mv Dockerfile Dockerfile2
  - ls
  # - python igem-wikisync.py

after_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git add .
  - 'git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"'
  - git remote -v
  - git remote add deployed https://${GH_TOKEN}@github.com/igembitsgoa/igem-wikisync-test.git
  - git push deployed